### ISSUE TITLE
-cover not working

### ISSUE THREAD

**Issue by jchaves** [walle/gimli#63]
I'm trying to figure out how to merge several .md files in certain order, and add a ToC and a cover as well. Well. What I'm doing is generating a list of the .md's, cat'ing them together into a new file (final.md), and then running this command:
```bash
gimli -cover cover.md -file final.md -outputfilename definitive -w '--toc --footer-right "[page]/[toPage]"'
```
If I leave out the "-cover cover.md" part, it works perfectly. (Thanks for your work, btw!). But I seems like there were a bug with the cover part. This is the message I'm getting:

```bash
/var/lib/gems/1.9.1/gems/gimli-0.5.7/lib/gimli/converter.rb:133:in `initialize': Permission denied - /var/lib/gems/1.9.1/gems/gimli-0.5.7/config/cover.html (Errno::EACCES)
        from /var/lib/gems/1.9.1/gems/gimli-0.5.7/lib/gimli/converter.rb:133:in `open'
        from /var/lib/gems/1.9.1/gems/gimli-0.5.7/lib/gimli/converter.rb:133:in `generate_cover!'
        from /var/lib/gems/1.9.1/gems/gimli-0.5.7/lib/gimli/converter.rb:65:in `output_pdf'
        from /var/lib/gems/1.9.1/gems/gimli-0.5.7/lib/gimli/converter.rb:36:in `block in convert!'
        from /var/lib/gems/1.9.1/gems/gimli-0.5.7/lib/gimli/converter.rb:29:in `each'
        from /var/lib/gems/1.9.1/gems/gimli-0.5.7/lib/gimli/converter.rb:29:in `convert!'
        from /var/lib/gems/1.9.1/gems/gimli-0.5.7/lib/gimli.rb:31:in `process!'
        from /var/lib/gems/1.9.1/gems/gimli-0.5.7/bin/gimli:25:in `<top (required)>'
        from /usr/local/bin/gimli:23:in `load'
        from /usr/local/bin/gimli:23:in `<main>'
```

(inside /var/lib/gems/1.9.1/gems/gimli-0.5.7/config/, there's only a file, **style.css** )

I don't know if this is still a WIP, but I thought it's a nice feature and I'd like to get it working... am I missing something?

My env:
Ubuntu 13.10 , ruby 1.9.3p194, gimli 0.5.7, wkhtmltopdf 0.9.6 (maybe too old, now that I see it?. It seems to support  "--cover"...), and I'm not sure about any other info you could need, hehe. Just let me know if so.

Thanks!

**Comment by walle** [comment]
I took a quick look at the code and it seems like it's working like intended (but should be changed to work like you are using it I think). This feature is a pull request from @k0kubun, I will get in touch with the contributor and discuss changes to the functionality.
The code in question is here https://github.com/walle/gimli/blob/development/lib/gimli/converter.rb#L22
For now, put your cover.md in the config directory (as cover.html) and run gimli using the `-cover` flag.
I think we will update this functionality for the next release (0.6 then because someone might be using the current behaviour).

@k0kubun what are your thoughts about this issue? Should we change the -cover code to take a file as parameter and scrap the `../config/`code? Could we document this better in the README?

**Comment by walle** [comment]
And for concatenating the files you could use the `-m` flag to merge all .md files to one pdf. To do this point gimli to a folder with the `-f` flag (or use current directory by skipping the `-f` flag). Gimli merges the files in alphabetical order and a common pattern is to name the files 1_1_foo.md, 1_2_bar.md, 2_1_foo.md, 2_2_bar.md to get them in the right order. This will also add a page break between pages, so each .md file will start on a new page in the .pdf.

And thank you for reporting the issue and using the application :)

**Comment by k0kubun** [comment]
I reviewed my code slightly. I thought my implementation is bad. Sometimes using gem-internal directory may cause permission error.
Maybe using `Tempfile` is enough for cover.html. Creating a file by `Tempfile` will not be denied.

**Comment by walle** [comment]
@k0kubun feel free to open a new pull request if you feel you have a good solution for the problem. We can continue the discussion there then.
